<?php

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 *
 * @see \Drupal\views\Tests\Plugin\CacheTest
 * @see \Drupal\views\Tests\Plugin\RenderTest
 */
function rt_module_views_pre_render(ViewExecutable $view) {
 # dsm($view->id(),"id");
 # dsm($view->current_display,"cr");
  if (isset($view) && ($view->id() == 'newjoiners_timeline' ) ) {
    switch ($view->current_display) {
      case 'newjoiner_timeliners_page':
        $view->element['#attached']['library'][] = 'rt_module/timelinerjs';
        break;
      case 'newjoiners_timelify_page':
        $view->element['#attached']['library'][] = 'rt_module/timelifyjs';
        break;
      case 'newjoiner_innovators_page':
        $view->element['#attached']['library'][] = 'rt_module/innovators';
        break;
      case 'newjoiner_2sidedcard_page':
        $view->element['#attached']['library'][] = 'rt_module/2sidedcard';
        break;
      case 'newjoiner_usercards_page':
        $view->element['#attached']['library'][] = 'rt_module/usercards';
      break;
      case 'newjoiner_contactme_page':
        $view->element['#attached']['library'][] = 'rt_module/contactme';
      break;
      default:
        # code...
        break;
    }

  }


}

function rt_module_preprocess_views_view(&$variables) {
  $view = $variables['view'];
  #dsm($view->current_display,"cr");
  if (isset($view) && ($view->id() == 'newjoiners_timeline' ) ) {
    switch ($view->current_display) {
      case 'newjoiner_timeliners_page':
        $variables['attributes']['class'][] = 'timeline-wrapper-newjoiners';
        break;
      case 'newjoiners_timelify_page':
        $variables['attributes']['class'][] = 'timeline';
        break;
      case 'newjoiner_innovators_page':
        // $view->element['#attached']['library'][] = 'rt_module/innovators';
        break;
      case 'newjoiner_2sidedcard_page':
        // $view->element['#attached']['library'][] = 'rt_module/2sidedcard';
        break;
      case 'newjoiner_usercards_page':
        $variables['attributes']['class'][] = 'timeline';
      break;
      case 'newjoiner_contactme_page':
        // $view->element['#attached']['library'][] = 'rt_module/contactme';
      break;
      default:
        # code...
        break;
    }

  }

}
